### ISSUE TITLE
Google Oauth not working

### ISSUE THREAD

**Issue by HarshitPG** [pooja-gera/algorithm-finder#18]
The google oauth is not functioning.
I would like to be assigned to this issue.

**Comment by pooja-gera** [comment]
Hello @HarshitPG thankyou for pointing it out. It’s broken because I had some security concerns over doing the auth completely over FE hence wanted to shift this to the BE of this tool. So effectively Google OAuth is not required in this repo as of now. It’s wonderful that you took the time to try the code 😋
